all:
	make -C ./points1
	make -C ./triangle1
	make -C ./triangle2
	make -C ./texture1
	make -C ./nehe
	make -C ./depthbug

clean:
	make clean -C ./points1
	make clean -C ./triangle1
	make clean -C ./triangle2
	make clean -C ./texture1
	make clean -C ./nehe
	make clean -C ./depthbug

.PHONY: all clean
